export { default as Login } from './Login';
export { default as Main } from './Main';
export { default as MyPage } from './MyPage';
export { default as Save } from './Save';
export { default as SaveComplete } from './Save/SaveComplete';
export { default as Vote } from './Vote';
export { default as VoteComplete } from './Vote/VoteComplete';
export { default as SaveRecord } from './SaveRecord';
export { default as Redirect } from './Redirect';
