# 메인 브랜치에 푸시 발생 시 실행됨
name: S3 Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

        # Github Repository Secrets 이용해 리액트 파일 내 환경 변수 파일 생성
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_IMGUR_URL=$REACT_APP_IMGUR_URL" >> .env.production
          echo "REACT_APP_IMGUR_CLIENT_ID=$REACT_APP_IMGUR_CLIENT_ID" >> .env.production
          echo "REACT_APP_IMGUR_CLIENT_PWD=$REACT_APP_IMGUR_CLIENT_PWD" >> .env.production
          echo "REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL" >> .env.production
          echo "REACT_APP_GOOGLE_OAUTH_SERVER=$REACT_APP_GOOGLE_OAUTH_SERVER" >> .env.production
          echo "REACT_APP_GOOGLE_OAUTH_REDIRECT_URL=$REACT_APP_GOOGLE_OAUTH_REDIRECT_URL" >> .env.production
          echo "REACT_APP_KAKAO_TOKEN=$REACT_APP_KAKAO_TOKEN" >> .env.production
        env:
          REACT_APP_IMGUR_URL: ${{ secrets.REACT_APP_IMGUR_URL }}
          REACT_APP_IMGUR_CLIENT_ID: ${{ secrets.REACT_APP_IMGUR_CLIENT_ID }}
          REACT_APP_IMGUR_CLIENT_PWD: ${{secrets.REACT_APP_IMGUR_CLIENT_PWD}}
          REACT_APP_SERVER_URL: ${{secrets.REACT_APP_SERVER_URL}}
          REACT_APP_GOOGLE_OAUTH_SERVER: ${{secrets.REACT_APP_GOOGLE_OAUTH_SERVER}}
          REACT_APP_GOOGLE_OAUTH_REDIRECT_URL: ${{secrets.REACT_APP_GOOGLE_OAUTH_REDIRECT_URL}}
          REACT_APP_KAKAO_TOKEN: ${{secrets.REACT_APP_KAKAO_TOKEN}}

      # package-lock.json의 변경 사항에 매번 패키지 새롭게 설치하지 않고 캐싱 진행
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      # package-lock.json 캐싱 결과에 따른 패키지 설치
      - name: Install
        run: npm install

      # 빌드 생성
      - name: Build
        run: npm run build

       # AWS S3 버킷 내 빌드 파일 업로드
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://${{ secrets.AWS_S3_Bucket_Name }}

      # cloudFront 내 저장된 캐시 무효화하여 새로운 리소스가 업데이트 되도록 함
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/index.html'
        continue-on-error: true
